services:
  postgres-product:
    image: 'postgres:latest'
    container_name: postgres-product
    environment:
      - 'POSTGRES_DB=products_db'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=admin'
    volumes:
      - products_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d products_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
#    networks:
#      - devsecops-project-net

  postgres-command:
    image: 'postgres:latest'
    container_name: postgres-command
    environment:
      - 'POSTGRES_DB=commands_db'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=admin'
    volumes:
      - commands_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d commands_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
#    networks:
#      - devsecops-project-net

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8088:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
#    networks:
#      - devsecops-project-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.4
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
#    networks:
#      - devsecops-project-net

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 60s

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
#      AUTH_SERVER: http://keycloak:8080/realms/devsecops-realm
      JWK_URI: http://keycloak:8080/realms/devsecops-realm/protocol/openid-connect/certs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
    depends_on:
      discovery-service:
        condition: service_healthy

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      DB_URL: jdbc:postgresql://postgres-product:5432/products_db
#      AUTH_SERVER: http://keycloak:8080/realms/devsecops-realm
      JWK_URI: http://keycloak:8080/realms/devsecops-realm/protocol/openid-connect/certs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 60s
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres-product:
        condition: service_healthy

  command-service:
    build: ./command-service
    container_name: command-service
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      DB_URL: jdbc:postgresql://postgres-command:5432/commands_db
#      AUTH_SERVER: http://keycloak:8080/realms/devsecops-realm
      JWK_URI: http://keycloak:8080/realms/devsecops-realm/protocol/openid-connect/certs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 60s
    depends_on:
      discovery-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
      postgres-command:
        condition: service_healthy

  front-end:
    build:
      context: ./front-end
      args:
        VITE_KEYCLOAK_URL: http://localhost:8080
        VITE_API_URL: http://localhost:8888
    container_name: front-end
    ports:
      - "5173:80"
    depends_on:
      keycloak:
        condition: service_started

  postgres-sonar:
    image: postgres:15
    container_name: postgres-sonar
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonar_pg_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - postgres-sonar
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-sonar:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  products_data:
  commands_data:
  pgadmin_data:
  keycloak_data:
  sonar_pg_data:
  sonar_data:
  sonar_extensions:

networks:
  devsecops-project-net:
    driver: bridge

